Synapxe-DNA/healthhub-content-optimization

.gitignore, notebooks/construct_graph.ipynb, notebooks/emb_sim_statistical.ipynb, notebooks/runner.ipynb
runner.ipynb - Modify to include d2v and statistical similarity
construct_graph.ipynb - Modify exact_match function and to export metrics
=> Modify construct_graph and runner

.pre-commit-config.yaml, notebooks/glove.ipynb
Removed `ruff-format` in `.pre-commit-config` so only `black` reformats; removed `fmt: off` comment in `glove.ipynb`
=> Updated .pre-commit-config

content-optimization/README.md, content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
- Added implementation to encode string to ASCII and back to UTF-8 to remove special symbols not found in ASCII encodings (e.g. copyright)
- Expanded tags from `h2 - h4` to `h1 - h6` to find all headers as per the HTML DOM structure
- Added implementation to create paragraphs between text sections using headers as reference breakpoint.
- Replace double newlines with single newlines and stripped whitespaces before and after the entire text
- Added warning for direct extraction of datasets into the `content_optimization/contentdata/01_raw/all_contents` directory
=> Merge kedro-text-preprocess into kedro-branch

content-optimization/conf/base/catalog.yml, content-optimization/conf/base/parameters_data_processing.yml, content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Edited both node functions in `nodes.py` to update `to_remove` columns to flag for articles that should be removed due to the missing or lack of content.
=> Edited function to flag articles for removal

content-optimization/src/content_optimization/pipelines/data_processing/nodes.py, content-optimization/src/content_optimization/utils/extract.py
- Reimplemented text extraction function to handle div and span containers
- Stripped whitespaces for all string values in dataframe
=> Merge `kedro-text-process` into `main`

content-optimization/README.md, content-optimization/conf/base/parameters_data_science.yml, content-optimization/src/content_optimization/pipelines/data_science/__init__.py, content-optimization/src/content_optimization/pipelines/data_science/nodes.py, content-optimization/src/content_optimization/pipelines/data_science/pipeline.py, content-optimization/tests/pipelines/data_science/test_pipeline.py
Created kedro `data_science` pipeline. This pipeline will mainly serves for clustering works.
=> Created kedro data_science pipeline

content-optimization/README.md, content-optimization/src/content_optimization/utils/extract.py
- Added Dataset Information on `merged_data.parquet`
- Updated function to clean text in `extract_links` and `extract_headers`
=> Merge `datasheet` into `main`

CHANGELOG.md, content-optimization/notebooks/presentation.ipynb
Modified `presentation.ipynb` such that it accounts for flagging of duplicated contents and duplicated URLs.
=> Modified presentation.ipynb

poetry.lock, pyproject.toml
- Removed Beanie
- Removed Motor
=> Removing deps from pyproject in repo root

backend/app/app/models/article.py, backend/app/app/scripts/populate_mongo/db_populator.py, backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py, backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py, backend/app/app/utils/db_connector/mongo_connector/mongo_connector_injector.py, backend/app/poetry.lock, backend/app/pyproject.toml, frontend/app/src/styles.css
- Updated backend to access "storage" collection in mongo
- Added "updated" field to articles
- Added bson back to poetry (for current endpoint usage)
=> Webapp use real data

content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
- Changed clean_up_fragments to instance method
- Added new punctuations to to clean up
- Added new condition in `_extract_text_from_strong` to check for punctuation at the end of the fragment to prevent string concatenation
- Handled edge cases for `_extract_text_from_p`
- Reimplemented counter for ordered lists
=> Update text processing pipeline to handle minor edge cases

content-optimization/README.md, content-optimization/src/content_optimization/pipelines/data_processing/extractor.py, content-optimization/src/content_optimization/pipelines/data_processing/nodes.py, content-optimization/src/content_optimization/pipelines/data_processing/utils.py
- Amended extract_links to ignore footnotes and online forms
- Replace En Dash with a dash to extract these dashes into extracted_content_body
- Implemented extract_tables method to extract tables as a 3d array (list of 2d tables)
- Created a function that can flag articles containing the given keyword. The flag is stored as a separate column
- Added extracted_tables as a new column to merged_data
- Updated columns to include extracted_tables
=> Improve Text Processing Pipeline

backend/app/app/data/example.ipynb, backend/app/app/interfaces/db_connector_types.py, backend/app/app/models/article.py, backend/app/app/models/generated_article.py, backend/app/app/models/job_combine.py, backend/app/app/routes/clusters/cluster_router.py, backend/app/app/scripts/populate_mongo/db_populator.py, backend/app/app/scripts/populate_mongo_mock/generators/mocker.py, backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py, backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
- Added Article Enum Status - Combine, Ignore, Optimise, Remove
- Added in labels - Labels => Generated Keywords - Keywords => Provided keywords
- Refactor variable names due to change in beanie documents
- Db_populator now use the method from db connector instead of its own methods
- Article Document id is now string instead of PydanticObjectId - Use the Article id provided by HH instead of letting mongodb generate
- Implemented abstract methods from db connector in mongo connector
-
=> Refactor and update populator

backend/app/app/interfaces/db_connector_types.py, backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py, backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
- Added abstract method for RemoveDocument
- Added remarks attribute to RemoveDocument
=> Webapp update schema lyndon

content-optimization/conf/base/parameters_data_processing.yml, content-optimization/notebooks/presentation.ipynb, content-optimization/src/content_optimization/pipelines/data_processing/nodes.py, content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py, content-optimization/src/content_optimization/pipelines/data_processing/utils.py, content-optimization/tests/pipelines/conftest.py, content-optimization/tests/pipelines/data_processing/test_nodes.py
Updated `parameters_data_processing.yml` configuration file to include a list of article IDs to be whitelisted as reviewed by Health Hub's team. Refer to this [Google Excel](https://docs.google.com/spreadsheets/d/1N39HV_LKo8bJ319uuFSCCrZrJEHfqoFb/edit?gid=1513013402#gid=1513013402) for more information. 
Updated `nodes.py` and `pipeline.py` to take in a new argument called `whitelist` (as named in `parameters_data_processing.yml`). This ensures that any article IDs whitelisted will still be processed — their content body extracted. 
Updated unit tests to ensure all articles eventually flagged for removal with the removal type "Below Word Count" actually falls below the word count, if not the test will fail. 
**Note:** For a full breakdown of the removal types, refer …
=> Updated `data_processing pipeline` to whitelist articles

article-harmonisation/README.md, article-harmonisation/models.py, article-harmonisation/prompt.py, article-harmonisation/prompts.py
- Amended docstrings for LLMPrompts
- Used appropriate Prompt Templates to facilitate better response generation across LLM models
- Added LLMPrompt Class for InternLM
- Used match statements instead of if-else for quicker retrieval of appropriate prompts
- Renamed Class Names for easier reference
- Updated README to reflect the change in the filename to prompts.py
- Updated import name from prompt.py to prompts.py
- Added a few models to try out for Llama, Phi3, Mistral and InternLM
- Updated `start_llm` to work with match statements for faster fetching of relevant models
- Updated docstrings for classes and functions
- Renamed function from `generate_text` to `generate_keypoints` for better readability
- Implemented dependency inversion to reduce nested conditions during function …
=> Article harmonisation issac

backend/app/app/scripts/populate_mongo_mock/generators/mocker.py, backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py
- Added missing variables for GeneratedArticleDocument
- Removed unused parameter in mocker
=> Clean up code for mocker and update beanie document

CHANGELOG.md, content-optimization/conf/base/parameters_data_processing.yml, content-optimization/src/content_optimization/pipelines/data_processing/nodes.py, content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py, content-optimization/src/content_optimization/pipelines/data_processing/utils.py
- Added blacklist dictionary into `parameters_data_processing.yml`
- Implemented `flag_articles_via_blacklist` function in utils.py to flag articles stated in YAML file
- Updated nodes.py and pipeline.py to include the `blacklist` parameter
- Updated changes to Kedro `data_processing` pipeline
=> Added blacklisted articles from clustering

content-optimization/src/content_optimization/pipelines/clustering/nodes.py
- Fix `update_edges_dataframe` function to the correct column name `new_cluster`
=> Modify update_edges_dataframe function in nodes.py

content-optimization/conf/base/catalog.yml, content-optimization/requirements.txt, content-optimization/src/content_optimization/pipelines/clustering/utils.py, content-optimization/src/content_optimization/pipelines/feature_engineering/nodes.py
- Added `alive_progress`, `einops`, `pyarrow`, `sentence-transformers`
- Added `nltk.download("stopwords")`
- Added `nltk.download("punkt_tab")`
- Fix variable names `unclustered_nodes` and `clustered_nodes` to` first_level_clustered_nodes` and `first_level_unclustered_nodes`
=> Add NLTK downloads and update requirements.txt

article-harmonisation/README.md, article-harmonisation/agents/models.py, article-harmonisation/agents/prompts.py, article-harmonisation/harmonisation.py, article-harmonisation/main_harmonisation.py, article-harmonisation/states/definitions.py, article-harmonisation/utils/excel_extractor.py, article-harmonisation/utils/formatters.py
- Added additional instructions for running article rewriting processes
- Added RunnableLambda with `parse_string_to_boolean` function under `evaluate_personality`
- Added docstrings for all functions to improve clarity of the code
- Added comments to improve clarity of the code
- Removed a `readability_evaluation_prompt` as it is no longer in use under article harmonisation.
- Added additional prompt under `return_content_prompt` that returns a template for the structure of a given article.
- Added docstrings for all functions to improve clarity of the code
- Added comments to improve clarity of the code
- Added docstrings for all functions to improve clarity of the code
- Added comments to improve clarity of the code
- Bug fixes
- Added docstrings for `optimise_articles` and …
=> Article harmonisation jc

article-harmonisation/README.md, article-harmonisation/checks.py, article-harmonisation/utils/formatters.py
- Added some spacing for print statements
- Cleaned up implementation for filtering given that the ids_for_optimisation.csv will already be filtered for generation
- Reorganised document structure to better use the markdown syntax
- Added required columns for optimisation checks workflow
- Renamed from Article Rewriting to Article Generation
- Renamed Name of README.md to Article Optimisation & Generation
- Removed `marked_articles` directory as it is no longer used
- Add `article_rewriting` directory to add inputs for article-harmonisation
=> Article harmonisation ij

content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
It is noted that the Kedroviz is not rendering all four of our pipelines onto the GitHub Page. It is only rendering three of the pipelines, and missing the `azure_rag` pipeline.
The issue is due to the `credentials.yml` file under `content-optimization\conf\local\`. This credentials.yml file is used in the `azure_rag` pipeline. This file is created locally, and is not pushed to GitHub due to it containing credentials, hence it is .gitkeep under content-optimization\conf\local. The steps to create the `credentials.yml` is detailed under `content-optimization\conf\README.md`
Therefore, when `kedro` viz is ran locally, it is able to display all pipelines including `zure_rag` pipeline.
However, since `credentials.yml` is not pushed to GitHub, thus in the Deployed GitHub Page, Kedroviz will …
=> Added dummy credentials to resolve kedro viz issue
